##########################################
# 
# Docker Projet Elective 
# 
# Members : 
#   Matteo Christophe
#   Romain Ranaivoson
#########################################

version: "3.9"

services:

  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - USER=dockerel
      - PASS=dockerel

    ports:
      - 9091:9091
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - tx-config:/config
      - torrent-downloads:/downloads
      - tx-watch:/watch
    restart: "unless-stopped"

    # Trafik redirect
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.localhost`)"
      - "traefik.http.routers.transmission.entrypoints=web"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
    networks:
      - medianet

  ###########################
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - radarr-config:/config
      - torrent-downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

    # Trafik redirect
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`radarr.localhost`)"
      - "traefik.http.routers.transmission.entrypoints=web"
      - "traefik.http.services.transmission.loadbalancer.server.port=7878"

    networks:
      - medianet

  ###########################
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

    # Trafik redirect
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`sonarr.localhost`)"
      - "traefik.http.routers.transmission.entrypoints=web"
      - "traefik.http.services.transmission.loadbalancer.server.port=8989"

    networks:
      - medianet

  ###########################
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jackett-config:/config
      - jackett-blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

    # Trafik redirect
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`jackett.localhost`)"
      - "traefik.http.routers.transmission.entrypoints=web"
      - "traefik.http.services.transmission.loadbalancer.server.port=9117"

    networks:
      - medianet

  ###########################
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

    # Trafik redirect
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`prowlarr.localhost`)"
      - "traefik.http.routers.transmission.entrypoints=web"
      - "traefik.http.services.transmission.loadbalancer.server.port=9696"

    networks:
      - medianet

  ###########################
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - torrent-downloads:/data
    devices:
      - /dev/dri:/dev/dri # Intel Quiksync
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920

    # Trafik redirect
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`jellyfin.localhost`)"
      - "traefik.http.routers.transmission.entrypoints=web"
      - "traefik.http.services.transmission.loadbalancer.server.port=8096"

    restart: unless-stopped
    networks:
      - medianet

  ###########################
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - medianet

  ###########################
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
 
networks:
  medianet:
    external: true

volumes:
  torrent-downloads:
  radarr-config:
  sonarr-config:
  jackett-config:
  jackett-blackhole:
  prowlarr-config:
  jellyfin-config:
  tx-config:
  tx-watch:

