##########################################
# 
# Docker Projet Elective 
# 
# Members : 
#   Matteo Christophe
#   Romain Ranaivoson
#########################################

version: "3.9"

services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - USER=admin
      - PASS=nimdatx

    ports:
      - 9091:9091
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - tx-config:/config
      - torrent-downloads:/downloads
      - tx-watch:/watch
    restart: "unless-stopped"

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - torrent-downloads:/downloads
    restart: "unless-stopped"

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jackett-config:/config
      - jackett-blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - torrent-downloads:/data
    devices:
      - /dev/dri:/dev/dri # Intel Quiksync
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --entrypoints.http.address=:80
      - --providers.docker=true
      - --api=true
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  ###########################
  whoami:
    image: containous/whoami
    labels:
      - traefik.http.routers.https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.https.entrypoints=https
      - traefik.http.routers.https.tls=true
      - traefik.http.routers.https.tls.certresolver=${CERT_RESOLVER}
 

volumes:
  torrent-downloads:
  radarr-config:
  sonarr-config:
  jackett-config:
  jackett-blackhole:
  prowlarr-config:
  jellyfin-config:
  tx-config:
  tx-watch:

networks:
  mynetwork:
    external: true
