version: "3.9"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run..sock:/var/run..sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myrouter.rule=Host(`www.bigdocker.com`)"
      - "traefik.http.routers.myrouter.entrypoints=web"
      - "traefik.http.routers.myrouter.tls=true"
      - "traefik.http.routers.myrouter.tls.certresolver=myresolver"
      - "traefik.http.services.myservice.loadbalancer.server.port=80"
    restart: unless-stopped
  ##########################
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    # user: 968:968
    restart: unless-stopped
    volumes:
      - ./jellyfin/config:/config
      - ./movies:/movies
      - ./series:/series
      - ./anime:/anime
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`stream.bigdocker.com`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
  ############################
  # Download stack
  ############################
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./prowlarr/config:/config
      - ./prowlarr/downloads:/downloads
    ports:
      - 9696:9696
    restart: unless-stopped

  ############################
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./sonarr/config:/config
      - ./series:/series
      - ./anime:/anime
      - all-downloads:/downloads
    ports:
      - 8989:8989
    depends_on:
      - prowlarr
    restart: unless-stopped

  ############################
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./radarr/config:/config
      - ./movies:/movies
      - all-downloads:/downloads
    ports:
      - 7878:7878
    depends_on:
      - prowlarr
    restart: unless-stopped

  ############################
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./lidarr/config:/config
      - ./lidarr/downloads:/downloads
      - ./lidarr/music:/music
      - all-downloads:/downloads
    ports:
      - 8686:8686
    depends_on:
      - prowlarr
    restart: unless-stopped

  #############################
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./transmission/config:/config
      - ./transmission/torrents:/torrents
      - all-downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

volumes:
  all-downloads:
